# roles/k8s_deployment/tasks/main.yml

- name: Install Nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  become: true
  service:
    name: nginx
    state: started
    enabled: true
