- name: Playbook to deploy k8s applications
  hosts:
    localhost:
    vars:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
  become: true

  tasks:
    - include_role:
        name: k8s_deployment
      vars:
        app_name: "app1"
        app_image: "nginx"
        replicas: 1
        namespace: "cbull"
        app_config: "hello"
